version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/project/client
    steps:
      - checkout:
          path: ~/project
      - run: npm install
      - run: npm run test
