version: 2
jobs:
  frontend:
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/project/client
    steps:
      - checkout:
          path: ~/project
      - run: npm install
      - run: npm install elm@latest-0.19.1
      - run: echo "export PATH=$PWD/node_modules/.bin:$PATH" >> $BASH_ENV
      - run: npm run test

  backend:
    docker:
      - image: circleci/python:3.7.5
    working_directory: ~/project/server
    steps:
      - checkout:
          path: ~/project
      - run: pip install --user poetry
      - run: echo "export PATH=$HOME/.local/bin/:$PATH" >> $BASH_ENV
      - run: poetry install
      - run: poetry run pytest
      - run: QUART_APP='app' poetry run quart openapi


workflows:
  version: 2
  build-app:
    jobs:
      - frontend
      - backend
